[package]
name = "api"
version = "0.1.0"
edition = "2021"
authors = ["Rob Caelers <rob.caelers@gmail.com>"]
license = "MIT"
description = "GuardRail: Gather Unanticipated Anomaly Reports, Debugging Reports and Anomaly Investigation Logs"
homepage = ""
repository = "https://github.com/rcaelers/guardrail"

[workspace]
members = [
    "migration"
]

[dependencies]
migration = { path = "migration" }
# Tokio
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["tracing", "io"] }
# Tower
tower-http = { version = "0.4", features = ["full"] }
# Axum/Web
axum = { version = "0.6.20", features = ["headers", "form", "query", "macros", "multipart", "tracing"] }
tera = { version = "1", default-features = false }
# Serde / json
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# SeaORM
sea-orm = { version = "^0.12.2", features = ["sqlx-postgres", "sqlx-sqlite", "runtime-tokio-rustls", "macros", "with-uuid", "with-json"] }
# Tracing
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["tracing-log", "local-time", "env-filter", "json"] }
tracing-appender = "0.2"
# Minidump processing
minidump = { version = "0.17.0" }
minidump-processor = { version = "0.17.0" }
minidump-unwind = { version = "0.17.0", features = ["debuginfo", "http"] }
# Others
futures = "0.3.28"
async-trait = "0.1.73"
uuid = { version = "1", features = ["v4", "fast-rng", "serde", "std"] }
mime = "0.3.17"
rand = { version = "0.8.5", features = ["small_rng", "serde1"] }
config = "0.13.3"

# anyhow = "1"
thiserror = "1.0.47"
chrono = { version = "0.4.28", features = ["serde"] }

[features]
dump_syms = ["minidump-processor/dump_syms"]

[dev-dependencies]
axum-test = "12.2.0"
serial_test = "2"
