##
## Builder
##

FROM node:22-alpine AS builder

WORKDIR /build

COPY src/web/ui/package*.json ./
RUN npm ci

COPY src/web/ui/ .
RUN npm run build

#
# Runtime
#

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /build/build .

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["node", "index.js"]
