##
## Builder
##

FROM --platform=$BUILDPLATFORM rustlang/rust:stable-alpine AS builder

ENV RUSTUP_PERMIT_COPY_RENAME=true

RUN apk add --no-cache \
    clang \
    openssl \
    pkgconfig \
    openssl-dev \
    openssl-libs-static \
    musl-dev \
    build-base \
    nodejs \
    npm

RUN mkdir -p /app
WORKDIR /app
COPY . .

RUN npm install
RUN npm run web:islands:build
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=target-web,target=/app/target \
    cargo build --release -p web && \
    cp /app/target/release/web /app/web-bin

#
# Runtime
#

FROM alpine:latest

RUN addgroup -g 1000 -S guardrail && adduser -u 1000 -S guardrail -G guardrail

WORKDIR /app

RUN apk add --no-cache openssl ca-certificates tzdata tini && \
    rm -rf /var/cache/apk/*

COPY --from=builder /app/web-bin /app/web
COPY --from=builder /app/src/web/server/static /app/static

RUN mkdir -p /app/config && \
    chown -R guardrail:guardrail /app

VOLUME ["/app/config"]

USER guardrail

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/app/web", "-C", "/app/config"]
