##
## Builder
##

FROM oven/bun:1-alpine AS builder

WORKDIR /build

COPY src/web/ui/package.json ./
RUN bun install

COPY src/web/ui/ .
RUN bun run build

#
# Runtime
#

FROM oven/bun:1-alpine

WORKDIR /app

COPY --from=builder /build/build .

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["bun", "index.js"]
