##
## Builder
##

FROM oven/bun:1-alpine AS builder

WORKDIR /build

COPY src/web/ui/package.json src/web/ui/package-lock.json ./
RUN bun install

COPY src/web/ui/ .
RUN bun run build

#
# Development
#

FROM oven/bun:1-alpine AS dev

WORKDIR /app

COPY src/web/ui/package.json src/web/ui/package-lock.json ./
RUN bun install

COPY src/web/ui/ .

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

#
# Runtime
#

FROM oven/bun:1-alpine

WORKDIR /app

COPY --from=builder /build/build .

ENV PORT=3000
ENV HOST=0.0.0.0

EXPOSE 3000

CMD ["bun", "index.js"]
