##
## Chef
##

FROM --platform=$BUILDPLATFORM rust:alpine3.23 AS chef

RUN apk add --no-cache \
    clang \
    mold \
    openssl \
    pkgconfig \
    openssl-dev \
    openssl-libs-static \
    musl-dev \
    build-base

RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    cargo install cargo-chef --locked

WORKDIR /app

##
## Planner
##

FROM chef AS planner

COPY . .
RUN cargo chef prepare --recipe-path recipe.json

##
## Builder
##

FROM chef AS builder

ENV RUSTUP_PERMIT_COPY_RENAME=true
ENV RUSTUP_TOOLCHAIN=stable
ARG CARGO_BUILD_JOBS=2
ENV CARGO_BUILD_JOBS=${CARGO_BUILD_JOBS}

COPY --from=planner /app/recipe.json recipe.json
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    cargo chef cook --release --recipe-path recipe.json -p web

COPY . .
RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry,sharing=locked \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git,sharing=locked \
    cargo build --release -p web && \
    cp /app/target/release/web /app/web-bin

#
# Runtime
#

FROM alpine:latest

RUN addgroup -g 1000 -S guardrail && adduser -u 1000 -S guardrail -G guardrail

WORKDIR /app

RUN apk add --no-cache openssl ca-certificates tzdata tini && \
    rm -rf /var/cache/apk/*

COPY --from=builder /app/web-bin /app/web
COPY --from=builder /app/src/web/server/static /app/static

RUN mkdir -p /app/config && \
    chown -R guardrail:guardrail /app

VOLUME ["/app/config"]

USER guardrail

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/app/web", "-C", "/app/config"]
