##
## Builder
##

FROM --platform=$BUILDPLATFORM rust:alpine3.23 AS builder

ENV RUSTUP_PERMIT_COPY_RENAME=true
ENV RUSTUP_TOOLCHAIN=stable

RUN apk add --no-cache \
    clang \
    mold \
    openssl \
    pkgconfig \
    openssl-dev \
    openssl-libs-static \
    musl-dev \
    build-base

RUN mkdir -p /app
WORKDIR /app
COPY . .

RUN --mount=type=cache,id=cargo-registry,target=/usr/local/cargo/registry \
    --mount=type=cache,id=cargo-git,target=/usr/local/cargo/git \
    --mount=type=cache,id=target-web,target=/app/target \
    cargo +stable build --release -p web && \
    cp /app/target/release/web /app/web-bin

#
# Runtime
#

FROM alpine:latest

RUN addgroup -g 1000 -S guardrail && adduser -u 1000 -S guardrail -G guardrail

WORKDIR /app

RUN apk add --no-cache openssl ca-certificates tzdata tini && \
    rm -rf /var/cache/apk/*

COPY --from=builder /app/web-bin /app/web
COPY --from=builder /app/src/web/server/static /app/static

RUN mkdir -p /app/config && \
    chown -R guardrail:guardrail /app

VOLUME ["/app/config"]

USER guardrail

ENTRYPOINT ["/sbin/tini", "--"]

CMD ["/app/web", "-C", "/app/config"]
