//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

pub mod prelude;

pub mod annotation;
pub mod attachment;
pub mod crash;
pub mod credential;
pub mod product;
pub mod sea_orm_active_enums;
pub mod session;
pub mod symbols;
pub mod user;
pub mod version;
