//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::annotation::Entity as Annotation;
pub use super::attachment::Entity as Attachment;
pub use super::crash::Entity as Crash;
pub use super::credential::Entity as Credential;
pub use super::product::Entity as Product;
pub use super::session::Entity as Session;
pub use super::symbols::Entity as Symbols;
pub use super::user::Entity as User;
pub use super::version::Entity as Version;
