volumes:
  postgresql17-storage:
  pgadmin4-storage:
  garage-data:
  garage-meta:

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgresql17-storage:/var/lib/postgresql/data
      - ./initdb/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -U postgres"
      interval: 30s
      timeout: 10s
      retries: 6

  postgrest:
    container_name: postgrest
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    volumes:
      - ./ed25519-jwk.json:/ed25519-jwk.json
    environment:
      PGRST_DB_URI: postgres://authenticator:wezei4Joozooz8To@postgresql:5432/guardrail
      PGRST_ADMIN_SERVER_PORT: 3001
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_SCHEMAS: "guardrail"
      PGRST_DB_ANON_ROLE: "guardrail_anonymous"
      PGRST_JWT_SECRET: "@/ed25519-jwk.json"
      PGRST_LOG_LEVEL: "debug"
    depends_on:
      - postgresql

  swagger:
    container_name: swagger
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000/

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - 11000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=rob.caelers@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgadmin4-storage:/var/lib/pgadmin
    depends_on:
      - postgresql
    restart: unless-stopped

  garage:
    container_name: garage
    image: dxflrs/garage:v1.1.0
    ports:
      - 3900:3900
      - 3901:3901
      - 3902:3902
      - 3903:3903
    volumes:
      - garage-data:/var/lib/garage/data
      - garage-meta:/var/lib/garage/meta
      - ./garage-config/garage.toml:/etc/garage.toml
    environment:
      - RUST_LOG=debug
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3900/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
