volumes:
  surrealdb-storage:
  minio-storage:
  valkey-storage:

services:
  valkey:
    container_name: valkey
    image: valkey/valkey:latest
    ports:
      - 6379:6379
    volumes:
      - valkey-storage:/data
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'valkey-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    user: '0:0'
    ports:
      - 8000:8000
    volumes:
      - surrealdb-storage:/data
    command: start --user root --pass root rocksdb:/data/srdb.db
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'surreal', 'is-ready', '--conn', 'http://localhost:8000']
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000' # S3 API port
      - '9001:9001' # Console port
    volumes:
      - minio-storage:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    healthcheck:
      test: ['CMD', 'mc', 'ready', 'local']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio-setup:
    image: minio/mc
    container_name: minio-setup
    depends_on:
      minio:
        condition: service_healthy
    volumes:
      - ./minio-setup.sh:/minio-setup.sh
    entrypoint: ['/bin/sh', '-c', 'chmod +x /minio-setup.sh && /minio-setup.sh']
    restart: 'no'
