#!/bin/sh
# Generates the local-only secrets consumed by deploy/docker-compose.yml.
#
# Mirrors the split between workrave-infra's non-secret ConfigMaps (checked
# into deploy/config/) and its SOPS-encrypted Secrets (generated here into
# deploy/_private/, which is gitignored). Safe to re-run: existing values in
# deploy/.env are reused so already-bootstrapped state (SurrealDB root password,
# Garage keys, the Pocket ID OIDC client secret) doesn't get rotated out from
# under a running stack.
set -eu
umask 077

BASEDIR=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
ENV_FILE="$BASEDIR/.env"
PRIVATE_DIR="$BASEDIR/_private"
CONFIG_SECRETS_DIR="$PRIVATE_DIR/config"
GARAGE_SECRETS_DIR="$PRIVATE_DIR/garage"
mkdir -p "$CONFIG_SECRETS_DIR" "$GARAGE_SECRETS_DIR" "$PRIVATE_DIR/pocket-id" "$PRIVATE_DIR/certs"
chmod 700 "$PRIVATE_DIR" "$CONFIG_SECRETS_DIR" "$GARAGE_SECRETS_DIR"

log() { printf '%s\n' "$*"; }

rand_hex() { openssl rand -hex 32; }

# Load any values already generated on a previous run so we don't rotate
# secrets that other services (Pocket ID, Garage, SurrealDB) have already
# bootstrapped against.
COMPOSE_SETTINGS=''
if [ -f "$ENV_FILE" ]; then
  # Keep local Compose selection and remote bind paths when rewriting secrets.
  # Otherwise a routine setup rerun silently falls back to client-side mounts.
  COMPOSE_SETTINGS=$(sed -n \
    -e '/^COMPOSE_/p' \
    -e '/^DOCKER_BUILDKIT=/p' \
    -e '/^GUARDRAIL_DEPLOY_DIR=/p' \
    -e '/^GUARDRAIL_UI_DIR=/p' "$ENV_FILE")
  # shellcheck disable=SC1090
  . "$ENV_FILE"
fi

: "${SURREALDB_ROOT_PASSWORD:=$(rand_hex)}"
: "${VALKEY_PASSWORD:=$(rand_hex)}"
: "${GARAGE_RPC_SECRET:=$(rand_hex)}"
: "${GARAGE_ADMIN_TOKEN:=$(rand_hex)}"
: "${GARAGE_METRICS_TOKEN:=$(rand_hex)}"
: "${GARAGE_ACCESS_KEY:=GK$(openssl rand -hex 10)}"
: "${GARAGE_SECRET_KEY:=$(rand_hex)}"
: "${POCKET_ID_ENCRYPTION_KEY:=$(rand_hex)}"
: "${POCKET_ID_STATIC_API_KEY:=$(rand_hex)}"
: "${GUARDRAIL_OIDC_CLIENT_SECRET:=$(rand_hex)}"

log "Writing $ENV_FILE"
cat >"$ENV_FILE" <<EOF
# Generated by deploy/generate-secrets.sh — local dev only, never commit.
# Re-run the script to fill in anything missing; existing values are kept.
SURREALDB_ROOT_PASSWORD=$SURREALDB_ROOT_PASSWORD
VALKEY_PASSWORD=$VALKEY_PASSWORD
GARAGE_RPC_SECRET=$GARAGE_RPC_SECRET
GARAGE_ADMIN_TOKEN=$GARAGE_ADMIN_TOKEN
GARAGE_METRICS_TOKEN=$GARAGE_METRICS_TOKEN
GARAGE_ACCESS_KEY=$GARAGE_ACCESS_KEY
GARAGE_SECRET_KEY=$GARAGE_SECRET_KEY
POCKET_ID_ENCRYPTION_KEY=$POCKET_ID_ENCRYPTION_KEY
POCKET_ID_STATIC_API_KEY=$POCKET_ID_STATIC_API_KEY
GUARDRAIL_OIDC_CLIENT_SECRET=$GUARDRAIL_OIDC_CLIENT_SECRET
EOF
if [ -n "$COMPOSE_SETTINGS" ]; then
  printf '\n%s\n' "$COMPOSE_SETTINGS" >>"$ENV_FILE"
fi
chmod 600 "$ENV_FILE"

# Keep an existing key; a fresh environment gets its own matching keypair.
if [ ! -f "$BASEDIR/_private/development-private.pem" ]; then
  log "Generating development JWK keypair"
  openssl genpkey -algorithm ed25519 -out "$PRIVATE_DIR/development-private.pem"
fi
JWK_PRIVATE_KEY=$(cat "$BASEDIR/_private/development-private.pem")
JWK_PUBLIC_KEY=$(openssl pkey -in "$PRIVATE_DIR/development-private.pem" -pubout)

log "Writing $CONFIG_SECRETS_DIR/*.yaml"

cat >"$CONFIG_SECRETS_DIR/02-valkey-secret.yaml" <<EOF
valkey:
  uri: redis://default:${VALKEY_PASSWORD}@valkey:6379
EOF

cat >"$CONFIG_SECRETS_DIR/03-object-storage-secret.yaml" <<EOF
object_storage:
  access_key_id: "${GARAGE_ACCESS_KEY}"
  secret_access_key: "${GARAGE_SECRET_KEY}"
EOF

cat >"$CONFIG_SECRETS_DIR/04-jwk-secret.yaml" <<EOF
database:
  jwk:
    public_key: |
$(printf '%s\n' "$JWK_PUBLIC_KEY" | sed 's/^/      /')
    private_key: |
$(printf '%s\n' "$JWK_PRIVATE_KEY" | sed 's/^/      /')
EOF

# The bootstrap service replaces this placeholder with Pocket ID's real
# secret. Do not reset it when preparing an already-running environment.
if [ ! -f "$CONFIG_SECRETS_DIR/04-oidc-secret.yaml" ]; then
  cat >"$CONFIG_SECRETS_DIR/04-oidc-secret.yaml" <<EOF
oidc:
  client_secret: "${GUARDRAIL_OIDC_CLIENT_SECRET}"
EOF
fi

cat >"$CONFIG_SECRETS_DIR/05-provisioner-secret.yaml" <<EOF
provisioner:
  pocket_id:
    api_key: "${POCKET_ID_STATIC_API_KEY}"
EOF

cat >"$CONFIG_SECRETS_DIR/06-database-secret.yaml" <<EOF
database:
  username: root
  password: "${SURREALDB_ROOT_PASSWORD}"
EOF

if [ ! -f "$CONFIG_SECRETS_DIR/07-email-secret.yaml" ]; then
  cat >"$CONFIG_SECRETS_DIR/07-email-secret.yaml" <<EOF
email:
  resend:
    key: ""
EOF
fi

log "Writing $GARAGE_SECRETS_DIR/*"
printf '%s' "$GARAGE_RPC_SECRET" >"$GARAGE_SECRETS_DIR/rpc_secret"
printf '%s' "$GARAGE_ADMIN_TOKEN" >"$GARAGE_SECRETS_DIR/admin_token"
printf '%s' "$GARAGE_METRICS_TOKEN" >"$GARAGE_SECRETS_DIR/metrics_token"

CERT="$PRIVATE_DIR/certs/guardrail.home.krandor.org.crt"
KEY="$PRIVATE_DIR/certs/guardrail.home.krandor.org.key"
if [ ! -f "$CERT" ] && [ ! -f "$KEY" ]; then
  log "Generating a self-signed development TLS certificate"
  openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
    -subj '/CN=guardrail.home.krandor.org' \
    -addext 'subjectAltName=DNS:guardrail.home.krandor.org' \
    -keyout "$KEY" -out "$CERT" 2>/dev/null
elif [ ! -f "$CERT" ] || [ ! -f "$KEY" ]; then
  log "Incomplete TLS keypair: provide both $CERT and $KEY" >&2
  exit 1
fi

log "Done. On first boot, pocket-id-setup replaces the OIDC placeholder with"
log "the real client secret before guardrail-web starts. Existing OIDC and"
log "email settings are preserved."
