#!/bin/sh
# Generates the local-only secrets consumed by dev/docker-compose.yml.
#
# Mirrors the split between workrave-infra's non-secret ConfigMaps (checked
# into dev/config/) and its SOPS-encrypted Secrets (generated here into
# dev/_private/, which is gitignored). Safe to re-run: existing values in
# dev/.env are reused so already-bootstrapped state (SurrealDB root password,
# Garage keys, the Pocket ID OIDC client secret) doesn't get rotated out from
# under a running stack.
set -eu

BASEDIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
ENV_FILE="$BASEDIR/.env"
PRIVATE_DIR="$BASEDIR/_private"
CONFIG_SECRETS_DIR="$PRIVATE_DIR/config"
GARAGE_SECRETS_DIR="$PRIVATE_DIR/garage"

log() { printf '%s\n' "$*"; }

rand_hex() { openssl rand -hex 32; }

# Load any values already generated on a previous run so we don't rotate
# secrets that other services (Pocket ID, Garage, SurrealDB) have already
# bootstrapped against.
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  . "$ENV_FILE"
fi

: "${SURREALDB_ROOT_PASSWORD:=$(rand_hex)}"
: "${VALKEY_PASSWORD:=$(rand_hex)}"
: "${GARAGE_RPC_SECRET:=$(rand_hex)}"
: "${GARAGE_ADMIN_TOKEN:=$(rand_hex)}"
: "${GARAGE_METRICS_TOKEN:=$(rand_hex)}"
: "${GARAGE_ACCESS_KEY:=GK$(openssl rand -hex 10)}"
: "${GARAGE_SECRET_KEY:=$(rand_hex)}"
: "${POCKET_ID_ENCRYPTION_KEY:=$(rand_hex)}"
: "${POCKET_ID_STATIC_API_KEY:=$(rand_hex)}"
: "${GUARDRAIL_OIDC_CLIENT_SECRET:=$(rand_hex)}"

log "Writing $ENV_FILE"
cat >"$ENV_FILE" <<EOF
# Generated by dev/generate-secrets.sh — local dev only, never commit.
# Re-run the script to fill in anything missing; existing values are kept.
SURREALDB_ROOT_PASSWORD=$SURREALDB_ROOT_PASSWORD
VALKEY_PASSWORD=$VALKEY_PASSWORD
GARAGE_RPC_SECRET=$GARAGE_RPC_SECRET
GARAGE_ADMIN_TOKEN=$GARAGE_ADMIN_TOKEN
GARAGE_METRICS_TOKEN=$GARAGE_METRICS_TOKEN
GARAGE_ACCESS_KEY=$GARAGE_ACCESS_KEY
GARAGE_SECRET_KEY=$GARAGE_SECRET_KEY
POCKET_ID_ENCRYPTION_KEY=$POCKET_ID_ENCRYPTION_KEY
POCKET_ID_STATIC_API_KEY=$POCKET_ID_STATIC_API_KEY
GUARDRAIL_OIDC_CLIENT_SECRET=$GUARDRAIL_OIDC_CLIENT_SECRET
EOF

# The JWK keypair backing 01-database.yaml's public_key is checked into git
# (public keys aren't secret), so it must not be regenerated once created —
# doing so would desync it from the committed public key.
if [ ! -f "$BASEDIR/_private/development-private.pem" ]; then
  log "Generating development JWK keypair"
  "$BASEDIR/make_jwk_keys.sh" development
fi
JWK_PRIVATE_KEY=$(cat "$BASEDIR/_private/development-private.pem")

mkdir -p "$CONFIG_SECRETS_DIR" "$GARAGE_SECRETS_DIR"
chmod 700 "$PRIVATE_DIR" "$CONFIG_SECRETS_DIR" "$GARAGE_SECRETS_DIR"
umask 077

log "Writing $CONFIG_SECRETS_DIR/*.yaml"

cat >"$CONFIG_SECRETS_DIR/02-valkey-secret.yaml" <<EOF
valkey:
  uri: redis://default:${VALKEY_PASSWORD}@valkey:6379
EOF

cat >"$CONFIG_SECRETS_DIR/03-object-storage-secret.yaml" <<EOF
object_storage:
  access_key_id: "${GARAGE_ACCESS_KEY}"
  secret_access_key: "${GARAGE_SECRET_KEY}"
EOF

cat >"$CONFIG_SECRETS_DIR/04-jwk-secret.yaml" <<EOF
database:
  jwk:
    private_key: |
$(printf '%s\n' "$JWK_PRIVATE_KEY" | sed 's/^/      /')
EOF

cat >"$CONFIG_SECRETS_DIR/04-oidc-secret.yaml" <<EOF
oidc:
  client_secret: "${GUARDRAIL_OIDC_CLIENT_SECRET}"
EOF

cat >"$CONFIG_SECRETS_DIR/05-provisioner-secret.yaml" <<EOF
provisioner:
  pocket_id:
    api_key: "${POCKET_ID_STATIC_API_KEY}"
EOF

cat >"$CONFIG_SECRETS_DIR/06-database-secret.yaml" <<EOF
database:
  username: root
  password: "${SURREALDB_ROOT_PASSWORD}"
EOF

cat >"$CONFIG_SECRETS_DIR/07-email-secret.yaml" <<EOF
email:
  resend:
    key: ""
EOF

log "Writing $GARAGE_SECRETS_DIR/*"
printf '%s' "$GARAGE_RPC_SECRET" >"$GARAGE_SECRETS_DIR/rpc_secret"
printf '%s' "$GARAGE_ADMIN_TOKEN" >"$GARAGE_SECRETS_DIR/admin_token"
printf '%s' "$GARAGE_METRICS_TOKEN" >"$GARAGE_SECRETS_DIR/metrics_token"

log "Done. The oidc.client_secret above is a placeholder — the pocket-id-setup"
log "service overwrites $CONFIG_SECRETS_DIR/04-oidc-secret.yaml with the real"
log "Pocket ID client secret on first boot; guardrail-web starts after it."
