server:
  port: 8080
  base_path: _data
  site: http://localhost:8080
logger:
  directory: _data/logs
  level: trace
database:
  uri: postgres://guardrail:wezei4Joozooz8To@localhost/guardrail
  user: postgres
  password: postgres
  name: postgres
auth:
  secret: secret
  issuer: https://idp.krandor.org
  client_id: 231190805631533098@guardrail 
  client_secret: ''
  redirect_uri: http://localhost:8080/auth/callback
  audiences:
    - '230305869814824983'
    - '230305928417706007@guardrail'
  scopes:
    - 'urn:zitadel:iam:org:project:roles' 
    - 'urn:zitadel:iam:user:metadata' 
    - 'urn:zitadel:iam:org:project:id:zitadel:aud'
