server:
  port: 4433
  base_path: _data
  site: https://guardrail.home.krandor.org:4433
logger:
  directory: _data/logs
  level: debug
database:
  uri: postgres://guardrail:wezei4Joozooz8To@localhost/guardrail
  user: postgres
  password: postgres
  name: postgres
auth:
  id: guardrail.home.krandor.org
  origin: https://guardrail.home.krandor.org:4433
  name: Guardrail
