web_server:
  port: 4433
  public_key: |
    -----BEGIN CERTIFICATE-----
    MIIFRTCCAy2gAwIBAgIUPEsUwWkKGlhvwLZzolvPcjjCE8wwDQYJKoZIhvcNAQEL
    BQAwMjELMAkGA1UEBhMCTkwxIzAhBgNVBAMMGmd1YXJkcmFpbC5ob21lLmtyYW5k
    b3Iub3JnMB4XDTI0MDQyMTAyNDQ1MFoXDTM0MDQxOTAyNDQ1MFowMjELMAkGA1UE
    BhMCTkwxIzAhBgNVBAMMGmd1YXJkcmFpbC5ob21lLmtyYW5kb3Iub3JnMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAod1kJfVeSMlU2akQeGBHQPCdphxc
    z1vmUptneAG50/dJBKAWlxFvSi2LEXOGG3g6+4Hmi251xEvGKhwuQti/OZyb9m7z
    EkG/cyjtQZqwQzctd3PYKfH4uEVr5du4UGjH3yO1xdeBMqRr77oDnMPpBHV/9xo2
    Ax9vfWDr+WJuQT100vtCppHy7os55yZT+EIUT9VjlT2M46FANKe+9y1RIjaO4+Gp
    SQdqUvWyI2+nBM6X5npWlHiB7OmYbejTcD0kGhZ5C2ulkfQlD6i5GRkQmKKIrgqC
    JKW1+Xu4UsqXUsvq/Dry4WmtviMIiFgTz/GcV3Dh3TYch92/VHU5ijwJ/wcRjDko
    uyJauPqN/idTcjg/je9oJ4xCUo638Ef+wpAIXN9MmRLOB/uaVWAVXzjgW0zo/DTt
    3NgUuEaqZewJYhxBslBpeVV/S5DAeod4hl6fhCR6dShCS8W1lgM9/wn/MK3VWV8i
    toWYj9Lkui6ShT8nCvnzDf7h5KuO0Zw5nPCAza3cUOG/i99HXu3Gk6AdNlrKeEX5
    ywheO2100CJfkb23FXmPBDecheISIprC54CGod3X78+BQBxZgKBwkWxzDNR2nMbU
    XaabqSLV40D2VcH2zwFtFiiNW7c3bTx5/CLpWBYQWR7G8QphYoU+GTRA+IneOmBb
    p6UWmOA6/se11IECAwEAAaNTMFEwHQYDVR0OBBYEFHfusTEcOZbFq7W5uB/abdBW
    M69HMB8GA1UdIwQYMBaAFHfusTEcOZbFq7W5uB/abdBWM69HMA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggIBAA6mtUzahe7J/8wCarO+NmkhjlXkQdPE
    Q4g/rhX7PPI0TGlyVcgc/O/OugZIefohDJHUB8DGdcO3k6gPOFzwF2bMQcMtagLf
    IxvE5Y34pdwlR5kD4h9Y11jZhw+cTKWv9m6zK5oEEtY5HzVCIV7jpUlw6ZLhVqR7
    Tl2OBVNUoWjAnkn4rLpr1ZNbe6laeGnvELHpd2j/WOekMohbWnnMeLP911k8bAei
    mBLKGjKHjQ8lFZxt95B0DSbFObyd8ApHVdoXQQxkm30fxn1ioXbxN3gjJ9CwFrwX
    CVGQYtVcoFnfVt26cqNM6t6QMGALnpCd8S15Kg4DDn3QXiDij/577DxdGwBTsDF2
    HtFysxhxhnpymY7NbeM6izOtvRbnaeCrvaryxZw3zUEQY8xcieUBHLmlIe+Qz6nM
    GmgfxsQQniwBR74+Nv9VsGB/G+CkzACyuZPxohttUr9MuHd24fpCVI4uyGrXD/gP
    heZcPJfDyp3ZvVAqH83QijV0eVAxUU9LykIB5wjW0imINUDPs0YVR+ABVNt273Hw
    zIQcGxveQCM8H0UF42ukf1dGI3y+Ns0EkgUsvqQAsH9xrVpn+KfjWF5LzONgUYHU
    FKj8ephsqEwKDHUVIAPfunr5nAKSeZmCOAQdCJd3z6S7j9imyXZgs5nabsjIapGB
    cHJs64x2VyU0
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCh3WQl9V5IyVTZ
    qRB4YEdA8J2mHFzPW+ZSm2d4AbnT90kEoBaXEW9KLYsRc4YbeDr7geaLbnXES8Yq
    HC5C2L85nJv2bvMSQb9zKO1BmrBDNy13c9gp8fi4RWvl27hQaMffI7XF14EypGvv
    ugOcw+kEdX/3GjYDH299YOv5Ym5BPXTS+0KmkfLuiznnJlP4QhRP1WOVPYzjoUA0
    p773LVEiNo7j4alJB2pS9bIjb6cEzpfmelaUeIHs6Zht6NNwPSQaFnkLa6WR9CUP
    qLkZGRCYooiuCoIkpbX5e7hSypdSy+r8OvLhaa2+IwiIWBPP8ZxXcOHdNhyH3b9U
    dTmKPAn/BxGMOSi7Ilq4+o3+J1NyOD+N72gnjEJSjrfwR/7CkAhc30yZEs4H+5pV
    YBVfOOBbTOj8NO3c2BS4Rqpl7AliHEGyUGl5VX9LkMB6h3iGXp+EJHp1KEJLxbWW
    Az3/Cf8wrdVZXyK2hZiP0uS6LpKFPycK+fMN/uHkq47RnDmc8IDNrdxQ4b+L30de
    7caToB02Wsp4RfnLCF47bXTQIl+RvbcVeY8EN5yF4hIimsLngIah3dfvz4FAHFmA
    oHCRbHMM1HacxtRdppupItXjQPZVwfbPAW0WKI1btzdtPHn8IulYFhBZHsbxCmFi
    hT4ZNED4id46YFunpRaY4Dr+x7XUgQIDAQABAoICABCfUIW4unDQGCIYGLm77WVP
    sGjawx8vnqn/Yoic6MKfQ5oxfyW5Y8vi0cQThdieqAlPBZLDtQgDs2XR/2Axq7A/
    aHbOCFvoxj/jGpD2UUE90odQrV4KsXzpnX3SlWLQjSyu7p+oFLuozfAlkpxlNAdC
    B8ejo0X+fZpgZdX2PpX9joM3dq3uEVwKOS0x2Zqw3S7Lnk6OWRXBPVDgTx30GJUN
    CZnWVpD02Cg31LjgjO7TRnR5PhiWKDA2VvHRNfFx80Soknqn7diyEUztNJZNZXpp
    6o5bmZIo4FSurgxL2MQRw9/DhVC9Dltsc+0IhSmsHrQ4wpZ51EPm85s5RJTxEHeR
    ul9Ha3na3Mpthmtzt1Ie5mSnG1GH6VpaQHY96ba4ag/Zr5t8jT0wgJNAJzHRNhWa
    e+Gs7Fvs3mBIBCP5m482CfxdsJVtBmU+OcSMBEoIDQbA0xSqV+ThwXECgOWa+AgD
    +s7Au9o9TStGXhTMBDE5RzhvPKLvgTeSDSBiR4ccTLNEGfOSULyn/kFk1rB9RdC4
    zzNF2dDp08kNuPQswSNQX7zo3ALkl1puvACfDgYfoSlRXoceaRPmUv29XpBDq9SQ
    qbEO/9/V01OaBsycl59mmcWzKpaPnvHxy1rbyrdWggyQ7a5o4yXND13MLWu74YOd
    pFysUvxs8fxM/UEAt/eXAoIBAQDaBrM7TC2v2jaq8cO5ljzB88gPcyZ0XB8Wtr/v
    8lq9m9jenOcif9wtqWlnljYb17AgI5WBgTqxHJmBrWcde5DlMGYq40EiMOp0yRQi
    IMVnx1f9KrGBUSYYVbPPnChjLyt/4ST0kBxKHlzihAMHdjgev374eDwt5XNHVOqR
    e2rQUITS5oDNUjkklnH19lT8EojyY9YUXhQLorBTYKeDpUL5SsCpjvyOG7WvAXCU
    Vhwcj2GA0XJC5cWtLMss8Z34+dY9shrjgOt2lEzErGTTOUxC2krnVsPVcMCMSC/0
    gDR/Jc8QFJzA54dvHr9oF13usmSnx36cabgl/OYECpwmpfrzAoIBAQC+DpTWBSDX
    127hdxq01xZGhSaazJ2dtSKTd/SXa8LPQYrAVAFHfelzglSKUPimkBih0Er8M6pA
    fmTVKeFRdZm4gJlut5GscalqDrANJvzUNxpdKqVtfxhj2rqZpx8f9rljlMQDarIT
    e/PAKgYO6aN8ZpgdtrWwPhY3tu9TOIXab0divxoIr+ClPcB3eJsmX2M0R5D60wL0
    qtlvET1xr4I7WJXVkB6qKNMpv5rDS60H0+QbrrZq/loOJQdyWx1ImfYGzECWylOS
    hW1EuzejaDNcdxQj6lKFArgPl9KsyRFRB6BQ46BF837f1F1u+YiP9KBngCFYJYLw
    hPy/0TCd8ae7AoIBAQCJSRzE4vQFvj8cJv4at1psuoeoCtcVAAjncY2slovCxwap
    Ll1wYNiQvBNOEczifU8+/YkfsfL2IU8b08eRTgRv/Kjoqo6R7AFGJnOSBdanwWNL
    W/3HswRs4FJIEUlxIvueG3P8t13I4hOU4pFRuoQeAHEAHh2uvMN5ECRgFTmuEHWC
    o3hJUVQAEOeTfFgJHdaz4l+kFZVDul6TMdJpV7+zX/mvCwVGqnYdy6dLEGnFJhe8
    WKY9L5fossMA+ueBJjhcQvEhfkVGNp2cXf1i77pwgioWP5EyrjvgWXgw2iW0Rmd6
    9a+63E9wjgjyj3wrWJN+/mRgM0WsTfG8a73lrDA3AoIBACVdEH2SvIYyYCYLGED9
    F+/9NT2xhDsA5S9AoeEy2jWMmQ5+dVHsuvxuXthiWr/EDFOjc1ppfcr4DjKp7RXq
    nLHc9k0B4a2ZGsky4gFz7Lh7rL8sJyGDnvPiiFS0ujW6d2/QS0iwrRmPgLgCivZb
    kDxgnv8YcFeZnRyO5jXiIs5ymgIbt66FhRB3N2NFXpsInaQlfacR3L7k56IiLYYw
    DtZD8BDwKFcjd3/5nx9NvVKQoYOfsVUPc/zb4r7kkrk3K1rixL/gPtXLTVP5ylJh
    pddDwb3dzyM/CZhnLI+zZ6gaa7X7SgL2f7bZNRUgEWzblr1CP0vo8/j87AN5yKkE
    XQkCggEBAJnSNI8Tiv3pPPNgOAsPhgfoaO6xpjFTjHHH/K08Pgj8HGwjcxyEyv/Y
    zhw2vRV0BMcxtm6eMV6nxTeD6CdbCXk+ZqiUD5TcTgfaxnzVGjJtIOfKN65ma/Td
    0aa9SElnXRiKB6T6LUpmCP2uTnGRwFg5X5aV2w93NQGVUmqDar8VcxliAOI84qUu
    JjCZfTD775/fNiUG1+U1ZZEOexj3OJRgQfl++yX2A1ysVRrGuWsYKi9dvXyIa0PY
    Qeqd8A0LJGwWC2dOVwmV06aN/txAvVPEG5KDJkJ6hLzi2BK+zpHz7RpnWn/H6Bgi
    kH89+JqlOvmRo8PEP2GF/hiNjlwfzwg=
    -----END PRIVATE KEY-----
api_server:
  port: 80
  public_keyx: |
    -----BEGIN CERTIFICATE-----
    MIIFRTCCAy2gAwIBAgIUPEsUwWkKGlhvwLZzolvPcjjCE8wwDQYJKoZIhvcNAQEL
    BQAwMjELMAkGA1UEBhMCTkwxIzAhBgNVBAMMGmd1YXJkcmFpbC5ob21lLmtyYW5k
    b3Iub3JnMB4XDTI0MDQyMTAyNDQ1MFoXDTM0MDQxOTAyNDQ1MFowMjELMAkGA1UE
    BhMCTkwxIzAhBgNVBAMMGmd1YXJkcmFpbC5ob21lLmtyYW5kb3Iub3JnMIICIjAN
    BgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAod1kJfVeSMlU2akQeGBHQPCdphxc
    z1vmUptneAG50/dJBKAWlxFvSi2LEXOGG3g6+4Hmi251xEvGKhwuQti/OZyb9m7z
    EkG/cyjtQZqwQzctd3PYKfH4uEVr5du4UGjH3yO1xdeBMqRr77oDnMPpBHV/9xo2
    Ax9vfWDr+WJuQT100vtCppHy7os55yZT+EIUT9VjlT2M46FANKe+9y1RIjaO4+Gp
    SQdqUvWyI2+nBM6X5npWlHiB7OmYbejTcD0kGhZ5C2ulkfQlD6i5GRkQmKKIrgqC
    JKW1+Xu4UsqXUsvq/Dry4WmtviMIiFgTz/GcV3Dh3TYch92/VHU5ijwJ/wcRjDko
    uyJauPqN/idTcjg/je9oJ4xCUo638Ef+wpAIXN9MmRLOB/uaVWAVXzjgW0zo/DTt
    3NgUuEaqZewJYhxBslBpeVV/S5DAeod4hl6fhCR6dShCS8W1lgM9/wn/MK3VWV8i
    toWYj9Lkui6ShT8nCvnzDf7h5KuO0Zw5nPCAza3cUOG/i99HXu3Gk6AdNlrKeEX5
    ywheO2100CJfkb23FXmPBDecheISIprC54CGod3X78+BQBxZgKBwkWxzDNR2nMbU
    XaabqSLV40D2VcH2zwFtFiiNW7c3bTx5/CLpWBYQWR7G8QphYoU+GTRA+IneOmBb
    p6UWmOA6/se11IECAwEAAaNTMFEwHQYDVR0OBBYEFHfusTEcOZbFq7W5uB/abdBW
    M69HMB8GA1UdIwQYMBaAFHfusTEcOZbFq7W5uB/abdBWM69HMA8GA1UdEwEB/wQF
    MAMBAf8wDQYJKoZIhvcNAQELBQADggIBAA6mtUzahe7J/8wCarO+NmkhjlXkQdPE
    Q4g/rhX7PPI0TGlyVcgc/O/OugZIefohDJHUB8DGdcO3k6gPOFzwF2bMQcMtagLf
    IxvE5Y34pdwlR5kD4h9Y11jZhw+cTKWv9m6zK5oEEtY5HzVCIV7jpUlw6ZLhVqR7
    Tl2OBVNUoWjAnkn4rLpr1ZNbe6laeGnvELHpd2j/WOekMohbWnnMeLP911k8bAei
    mBLKGjKHjQ8lFZxt95B0DSbFObyd8ApHVdoXQQxkm30fxn1ioXbxN3gjJ9CwFrwX
    CVGQYtVcoFnfVt26cqNM6t6QMGALnpCd8S15Kg4DDn3QXiDij/577DxdGwBTsDF2
    HtFysxhxhnpymY7NbeM6izOtvRbnaeCrvaryxZw3zUEQY8xcieUBHLmlIe+Qz6nM
    GmgfxsQQniwBR74+Nv9VsGB/G+CkzACyuZPxohttUr9MuHd24fpCVI4uyGrXD/gP
    heZcPJfDyp3ZvVAqH83QijV0eVAxUU9LykIB5wjW0imINUDPs0YVR+ABVNt273Hw
    zIQcGxveQCM8H0UF42ukf1dGI3y+Ns0EkgUsvqQAsH9xrVpn+KfjWF5LzONgUYHU
    FKj8ephsqEwKDHUVIAPfunr5nAKSeZmCOAQdCJd3z6S7j9imyXZgs5nabsjIapGB
    cHJs64x2VyU0
    -----END CERTIFICATE-----
  private_keyx: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCh3WQl9V5IyVTZ
    qRB4YEdA8J2mHFzPW+ZSm2d4AbnT90kEoBaXEW9KLYsRc4YbeDr7geaLbnXES8Yq
    HC5C2L85nJv2bvMSQb9zKO1BmrBDNy13c9gp8fi4RWvl27hQaMffI7XF14EypGvv
    ugOcw+kEdX/3GjYDH299YOv5Ym5BPXTS+0KmkfLuiznnJlP4QhRP1WOVPYzjoUA0
    p773LVEiNo7j4alJB2pS9bIjb6cEzpfmelaUeIHs6Zht6NNwPSQaFnkLa6WR9CUP
    qLkZGRCYooiuCoIkpbX5e7hSypdSy+r8OvLhaa2+IwiIWBPP8ZxXcOHdNhyH3b9U
    dTmKPAn/BxGMOSi7Ilq4+o3+J1NyOD+N72gnjEJSjrfwR/7CkAhc30yZEs4H+5pV
    YBVfOOBbTOj8NO3c2BS4Rqpl7AliHEGyUGl5VX9LkMB6h3iGXp+EJHp1KEJLxbWW
    Az3/Cf8wrdVZXyK2hZiP0uS6LpKFPycK+fMN/uHkq47RnDmc8IDNrdxQ4b+L30de
    7caToB02Wsp4RfnLCF47bXTQIl+RvbcVeY8EN5yF4hIimsLngIah3dfvz4FAHFmA
    oHCRbHMM1HacxtRdppupItXjQPZVwfbPAW0WKI1btzdtPHn8IulYFhBZHsbxCmFi
    hT4ZNED4id46YFunpRaY4Dr+x7XUgQIDAQABAoICABCfUIW4unDQGCIYGLm77WVP
    sGjawx8vnqn/Yoic6MKfQ5oxfyW5Y8vi0cQThdieqAlPBZLDtQgDs2XR/2Axq7A/
    aHbOCFvoxj/jGpD2UUE90odQrV4KsXzpnX3SlWLQjSyu7p+oFLuozfAlkpxlNAdC
    B8ejo0X+fZpgZdX2PpX9joM3dq3uEVwKOS0x2Zqw3S7Lnk6OWRXBPVDgTx30GJUN
    CZnWVpD02Cg31LjgjO7TRnR5PhiWKDA2VvHRNfFx80Soknqn7diyEUztNJZNZXpp
    6o5bmZIo4FSurgxL2MQRw9/DhVC9Dltsc+0IhSmsHrQ4wpZ51EPm85s5RJTxEHeR
    ul9Ha3na3Mpthmtzt1Ie5mSnG1GH6VpaQHY96ba4ag/Zr5t8jT0wgJNAJzHRNhWa
    e+Gs7Fvs3mBIBCP5m482CfxdsJVtBmU+OcSMBEoIDQbA0xSqV+ThwXECgOWa+AgD
    +s7Au9o9TStGXhTMBDE5RzhvPKLvgTeSDSBiR4ccTLNEGfOSULyn/kFk1rB9RdC4
    zzNF2dDp08kNuPQswSNQX7zo3ALkl1puvACfDgYfoSlRXoceaRPmUv29XpBDq9SQ
    qbEO/9/V01OaBsycl59mmcWzKpaPnvHxy1rbyrdWggyQ7a5o4yXND13MLWu74YOd
    pFysUvxs8fxM/UEAt/eXAoIBAQDaBrM7TC2v2jaq8cO5ljzB88gPcyZ0XB8Wtr/v
    8lq9m9jenOcif9wtqWlnljYb17AgI5WBgTqxHJmBrWcde5DlMGYq40EiMOp0yRQi
    IMVnx1f9KrGBUSYYVbPPnChjLyt/4ST0kBxKHlzihAMHdjgev374eDwt5XNHVOqR
    e2rQUITS5oDNUjkklnH19lT8EojyY9YUXhQLorBTYKeDpUL5SsCpjvyOG7WvAXCU
    Vhwcj2GA0XJC5cWtLMss8Z34+dY9shrjgOt2lEzErGTTOUxC2krnVsPVcMCMSC/0
    gDR/Jc8QFJzA54dvHr9oF13usmSnx36cabgl/OYECpwmpfrzAoIBAQC+DpTWBSDX
    127hdxq01xZGhSaazJ2dtSKTd/SXa8LPQYrAVAFHfelzglSKUPimkBih0Er8M6pA
    fmTVKeFRdZm4gJlut5GscalqDrANJvzUNxpdKqVtfxhj2rqZpx8f9rljlMQDarIT
    e/PAKgYO6aN8ZpgdtrWwPhY3tu9TOIXab0divxoIr+ClPcB3eJsmX2M0R5D60wL0
    qtlvET1xr4I7WJXVkB6qKNMpv5rDS60H0+QbrrZq/loOJQdyWx1ImfYGzECWylOS
    hW1EuzejaDNcdxQj6lKFArgPl9KsyRFRB6BQ46BF837f1F1u+YiP9KBngCFYJYLw
    hPy/0TCd8ae7AoIBAQCJSRzE4vQFvj8cJv4at1psuoeoCtcVAAjncY2slovCxwap
    Ll1wYNiQvBNOEczifU8+/YkfsfL2IU8b08eRTgRv/Kjoqo6R7AFGJnOSBdanwWNL
    W/3HswRs4FJIEUlxIvueG3P8t13I4hOU4pFRuoQeAHEAHh2uvMN5ECRgFTmuEHWC
    o3hJUVQAEOeTfFgJHdaz4l+kFZVDul6TMdJpV7+zX/mvCwVGqnYdy6dLEGnFJhe8
    WKY9L5fossMA+ueBJjhcQvEhfkVGNp2cXf1i77pwgioWP5EyrjvgWXgw2iW0Rmd6
    9a+63E9wjgjyj3wrWJN+/mRgM0WsTfG8a73lrDA3AoIBACVdEH2SvIYyYCYLGED9
    F+/9NT2xhDsA5S9AoeEy2jWMmQ5+dVHsuvxuXthiWr/EDFOjc1ppfcr4DjKp7RXq
    nLHc9k0B4a2ZGsky4gFz7Lh7rL8sJyGDnvPiiFS0ujW6d2/QS0iwrRmPgLgCivZb
    kDxgnv8YcFeZnRyO5jXiIs5ymgIbt66FhRB3N2NFXpsInaQlfacR3L7k56IiLYYw
    DtZD8BDwKFcjd3/5nx9NvVKQoYOfsVUPc/zb4r7kkrk3K1rixL/gPtXLTVP5ylJh
    pddDwb3dzyM/CZhnLI+zZ6gaa7X7SgL2f7bZNRUgEWzblr1CP0vo8/j87AN5yKkE
    XQkCggEBAJnSNI8Tiv3pPPNgOAsPhgfoaO6xpjFTjHHH/K08Pgj8HGwjcxyEyv/Y
    zhw2vRV0BMcxtm6eMV6nxTeD6CdbCXk+ZqiUD5TcTgfaxnzVGjJtIOfKN65ma/Td
    0aa9SElnXRiKB6T6LUpmCP2uTnGRwFg5X5aV2w93NQGVUmqDar8VcxliAOI84qUu
    JjCZfTD775/fNiUG1+U1ZZEOexj3OJRgQfl++yX2A1ysVRrGuWsYKi9dvXyIa0PY
    Qeqd8A0LJGwWC2dOVwmV06aN/txAvVPEG5KDJkJ6hLzi2BK+zpHz7RpnWn/H6Bgi
    kH89+JqlOvmRo8PEP2GF/hiNjlwfzwg=
    -----END PRIVATE KEY-----
job_server:
  port: 88
  db_uri: postgres://guardrail:wezei4Joozooz8To@localhost/apalis
database:
  db_uri: postgres://guardrail:wezei4Joozooz8To@localhost/guardrail
object_storage:
  region: us-east-1
  bucket: guardrail
  endpoint: http://localhost:9000
  allow_http: true
  access_key_id: "guardrail"
  secret_access_key: "guardrail"
auth:
  id: guardrail.home.krandor.org
  origin: https://guardrail.home.krandor.org:4433
  name: Guardrail
  jwk:
    token_validity_in_minutes: 30
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAJuN0TiFkCg0HnTjpisG1gfVY7XjKsFGuRm1JVmqkt74=
      -----END PUBLIC KEY-----"
    private_key: |
      -----BEGIN PRIVATE KEY-----
      MC4CAQAwBQYDK2VwBCIEILRksnzl63UUib+nmLsATtXc/EjOHMaMgJu+nbpiX068
      -----END PRIVATE KEY-----
