ingress:
  port: 4433
  base_url: https://guardrail.home.krandor.org:4433
  public_key: |
    -----BEGIN CERTIFICATE-----
    MIIEVTCCAj2gAwIBAgIBAjANBgkqhkiG9w0BAQsFADAbMRkwFwYDVQQDExBHdWFy
    ZHJhaWwgRGV2IENBMB4XDTI2MDQxODE2MDY1N1oXDTI3MDUyMDE2MDY1N1owJTEj
    MCEGA1UEAxMaZ3VhcmRyYWlsLmhvbWUua3JhbmRvci5vcmcwggEiMA0GCSqGSIb3
    DQEBAQUAA4IBDwAwggEKAoIBAQCpI9z5ChlVMMy1CxcRAzyffPswSEX4uzLL+rn5
    EZXMMkpP/uogV7HAE97vnZdfeakzv3K0nVFnmgLi6iQyjMSNFIdZ/wplex46x/P7
    bEeL59++CmM8cX+ilcAG2fdIkYEBt22+erJO707+sVuEv0DscE4B7RDBNT+0xMfe
    iZUQgOqf7nQS7KpHvvRjFcDVTsm1LDYgTKx3RfoJ00uBfikFWU3xhZJ8+W5cddwy
    4wka1pi0X4nnFRsrfzVeF2WoKkhSRe4GGnlsoQyIHmhP7FBz4fKv95t43wUJ/NFp
    J3aFMk9hGjzo+OYUXZbxuvFAmC9bRLezMTJcqUir03EhP7VnAgMBAAGjgZkwgZYw
    DgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAl
    BgNVHREEHjAcghpndWFyZHJhaWwuaG9tZS5rcmFuZG9yLm9yZzAdBgNVHQ4EFgQU
    +/WAz0REXm8HMFgaJsxHsUu7KJYwHwYDVR0jBBgwFoAUttipIAZ9OV2rQVbvYMaD
    /i99ggwwDQYJKoZIhvcNAQELBQADggIBAEB8g3LxkjahfHYpMgNIAdPbP73NvcAA
    lVWp7zFjdh8b6KgiCxfrkRg77c4CtAUIwQKPDvFwnla1825kwIBoAKzxdHrqEumG
    1nDls+GCu5uGTA5ukUoTO364btjTNHm/XIns+q/hkBqO6fQQcewJ2jvzlhOMMCok
    +nYAjIUBp2T0i4k/ZazfCh50ogKR+YeTj0U/ivnPLLKp7g0WXfudaLSHB9aSECod
    Mt1XKm+DdmTQFqzktMSXP8Azf/i3x2dcNrU2OnBD4WKnKmRXY9eRcu0ub9Q1y3xo
    TdB6UxSY0HYnigSv5V8GnvzWcjtqZa9vPLYUIfUrtt8ZMp1bEmMVJWUr4UJcqvOk
    a3E6O1OFlsAUJ4iYRhPdjzu50I58PaEqsUQzmt0rVI7/beUGNjns9wmaW64DxMag
    IFop5Z/FAFqt+rwDHHXyzRRaiv5C28ASO4Wbtz92BC/YidtWsVsqDaXAkXtvX1dn
    /ozvEBek/MrR1VLHibddnp+cakf8NSvuTYR5R+HZmNLIlRK3ETcRVwQH4v2LQ6ZU
    rDJbXJ1sLO8T7iaPoRRdzpr/NpNBLMNuT76FIjt062dXReOchDYci6Dv+xzCfllW
    aZwaMG4W3FD9wmwVPa93L2XZCNd2vhHPiaVIjNOKyMMEkWzBHOIaeGUkg612Ircm
    HLN2boxouJP6
    -----END CERTIFICATE-----
  private_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAqSPc+QoZVTDMtQsXEQM8n3z7MEhF+Lsyy/q5+RGVzDJKT/7q
    IFexwBPe752XX3mpM79ytJ1RZ5oC4uokMozEjRSHWf8KZXseOsfz+2xHi+ffvgpj
    PHF/opXABtn3SJGBAbdtvnqyTu9O/rFbhL9A7HBOAe0QwTU/tMTH3omVEIDqn+50
    EuyqR770YxXA1U7JtSw2IEysd0X6CdNLgX4pBVlN8YWSfPluXHXcMuMJGtaYtF+J
    5xUbK381XhdlqCpIUkXuBhp5bKEMiB5oT+xQc+Hyr/ebeN8FCfzRaSd2hTJPYRo8
    6PjmFF2W8brxQJgvW0S3szEyXKlIq9NxIT+1ZwIDAQABAoIBAAkVpAi8QiARPu16
    awK+6cKnM9akCx4Q7+mEzfhSuXj+On+RcYHLNADdEFxOWpMGNdBRuBd7W6P04bLO
    YKNWbDgnoh1zVVueAUGm+7PFXRJmod3TMQFOF0zkPiwgCOgc6JDvCTXx4SHcOKH1
    ZLT8kMAiSA5SbVPzSDitWQ7a1ObN7219iSGyyJOrZOsrx+dBp42YyIFF6PmsxWPb
    2TSFo0e2Fm7NZ3YE1TGDN+/JeXRIr0k5jzZ4muq6yHGqyjpwgdSOugNA87vne4LM
    7EzDu/PWVjXPYq6rOq7kKlpzAR88I6+M16kZy84kQla/5SBri/UzOsYM/662nn9v
    bQDtXAECgYEA2E4jz+iSgcVimhNieqgwjcIOSi6/zgolvO51fGHFRPAQS0b0u343
    5Qkgzaiue03YnjdQDY2a2iJQpa7ReB/ve8toYEyMlHR5mcqBh1N//62T5VLMXNFV
    mCj/oZ+joSs/pbiSWc+21cmtkGTAyfGbJAzwJo/Qv6M0p92m/qCDC3kCgYEAyC3w
    j0aTl7++oySYSXI9vSrybGA2A7Fc0NfJE8BjYMj3sNso0hd2P44Q4PCArousQ6ii
    p2bfY7PSZzcu9CI2amm76YIQ4Isew3KG1c8J76RkmB3s9FK+Rb4p5WpJ+ULf1Qa/
    N5ykna2XjeVARYpI8abTZ7xpVxvoB+2+KSsJr98CgYAQrW2rcRYitVJV6Nq19FPS
    Cj1J0PLu8u9X8tbSIUOxfgTzmOPztNagbSS/VpslXKowALnGYb2nxe+L5r+10FiJ
    pfRFQIGyTIy3o9p60aBT2VFG5Cxnl6hO1BJppsJaAdilcWavUAmb0DH2qR4IM/2v
    OOQnRP1mWTINI1Tl2wBfmQKBgQCnpxIabRmftk+Lg1Kn8K4UiKuQaOPUI++AWblm
    eXLB1I7d6C9ABbZbdDherA6aIRCdedcALQBbGHfXSjhg72ZzqSpgXzaTWPDi8EBN
    QaEou54kaKvT1JjXAHVGVsatpHyihYwQn3ifNov/o0k49KAzA217LCltc0nZmhvx
    jsIGMQKBgQCHrws0eWwwwW5ZqZMq0NGQEATogwzJT+EXSeR3ZEnLihW7XEFQnRka
    joy3l/GjSYckpTX4o17pr4GGlQiir4ppc8fPowzOlI2tjSCQv7aHr0sLKtjHjpmV
    Ty8f1c8nGOHJLE250Gu8QmN7LuAErFzlyRuOVg1F9QHMEevubg43ZQ==
    -----END RSA PRIVATE KEY-----
valkey:
  uri: redis://localhost:6379
processor:
  maximum_frame_count: 10
  delimiter: "|"
  skip_patterns:
  end_patterns:
    - "WinMainCRTStartup"
    - "mainCRTStartup"
    - "main()"
database:
  endpoint: ws://localhost:8000
  namespace: guardrail
  database: guardrail
  username: root
  password: root
  jwk:
    token_validity_in_minutes: 30
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAJuN0TiFkCg0HnTjpisG1gfVY7XjKsFGuRm1JVmqkt74=
      -----END PUBLIC KEY-----"
    private_key: |
      -----BEGIN PRIVATE KEY-----
      MC4CAQAwBQYDK2VwBCIEILRksnzl63UUib+nmLsATtXc/EjOHMaMgJu+nbpiX068
      -----END PRIVATE KEY-----
object_storage:
  region: us-east-1
  bucket: guardrail
  endpoint: http://localhost:9000
  allow_http: true
  access_key_id: "guardrail"
  secret_access_key: "guardrail"
email:
  from: "noreply@workrave.org"
oidc:
  issuer_url: https://guardrail.home.krandor.org:1443
  internal_issuer_url:
  client_id: guardrail
  client_secret: jCosZuGjbPkOp5rIb0xtTOYic9MmwwqL
  callback_url: https://guardrail.home.krandor.org:4433/auth/oidc/callback
  logout_callback_url: https://guardrail.home.krandor.org:4433
  launch_url: https://guardrail.home.krandor.org:4433
  self_service_url: https://guardrail.home.krandor.org:1443
  pkce: true
  allow_insecure_tls: true
