ingress:
  port: 80
  base_url: https://guardrail.home.krandor.org:4433
valkey:
  uri: redis://valkey:6379
processor:
  maximum_frame_count: 10
  delimiter: "|"
  skip_patterns:
  end_patterns:
    - "WinMainCRTStartup"
    - "mainCRTStartup"
    - "main()"
database:
  endpoint: ws://surrealdb:8000
  namespace: guardrail
  database: guardrail
  username: root
  password: root
  jwk:
    token_validity_in_minutes: 30
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAJuN0TiFkCg0HnTjpisG1gfVY7XjKsFGuRm1JVmqkt74=
      -----END PUBLIC KEY-----
    private_key: |
      -----BEGIN PRIVATE KEY-----
      MC4CAQAwBQYDK2VwBCIEILRksnzl63UUib+nmLsATtXc/EjOHMaMgJu+nbpiX068
      -----END PRIVATE KEY-----
object_storage:
  region: us-east-1
  bucket: guardrail
  endpoint: http://minio:9000
  allow_http: true
  access_key_id: "guardrail"
  secret_access_key: "guardrail"
email:
  from: "noreply@workrave.org"
oidc:
  issuer_url: https://guardrail.home.krandor.org:1443
  internal_issuer_url: http://pocket-id:1411
  client_id: guardrail
  client_secret: gNrzQUOszwg9ej2RRqCRCh5cw8HPUP25
  callback_url: https://guardrail.home.krandor.org:4433/auth/oidc/callback
  logout_callback_url: https://guardrail.home.krandor.org:4433
  launch_url: https://guardrail.home.krandor.org:4433
  self_service_url: https://guardrail.home.krandor.org:1443
  pkce: true
  allow_insecure_tls: true
