oidc:
  issuer_url: https://guardrail.home.krandor.org:2443/auth/v1
  internal_issuer_url: http://rauthy:8080/auth/v1
  client_id: guardrail
  client_secret: GuardrailRauthyDevClientSecret0123456789012345678901234567890123
provisioner:
  rauthy:
    api_url: http://rauthy:8080
    public_url: https://guardrail.home.krandor.org:2443/auth/v1
    api_key: guardrail$GuardrailRauthyDevApiKeySecret0123456789abcdefghijklmnopqrstuvwx
