//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod annotation;
pub mod attachment;
pub mod crash;
pub mod credential;
pub mod product;
pub mod role;
pub mod sea_orm_active_enums;
pub mod session;
pub mod symbols;
pub mod user;
pub mod version;
