name: Rust

on:
  push:
    branches: ["main", "dev"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main", "dev"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup upgrade
          cargo install --locked cargo-leptos
          cargo install --locked sqlx-cli
          cargo install --locked cargo-llvm-cov
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}
      - name: Build
        run: |
          export SQLX_OFFLINE=1
          cargo leptos build -vv
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test  -p api -p repos --no-fail-fast
