name: Rust

on:
  push:
    branches: ['main', 'dev']
    tags:
      - 'v*.*.*'
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup upgrade

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}
          cache-all-crates: 'true'

      - name: Build Svelte islands
        run: |
          npm i
          npm run web:islands:build

      - name: Build backend
        run: cargo build --workspace

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        run: |
          rustup toolchain install stable
          rustup default stable
          rustup upgrade

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-24.04
          cache-all-crates: 'true'

      - name: Install cargo-llvm-cov
        run: cargo install --locked cargo-llvm-cov

      - name: Build Svelte islands
        run: |
          npm i
          npm run web:islands:build

      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test -p api -p repos -p processor -p curator -p web --no-fail-fast
