name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [ubuntu-24.04, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup upgrade
          cargo install --locked cargo-leptos
      - name: Build
        run: cargo leptos build -vv
      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test --verbose
