name: Rust

on:
  push:
    branches: ['main', 'dev']
    tags:
      - 'v*.*.*'
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup upgrade

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.os }}
          cache-all-crates: 'true'

      - name: Install cargo-leptos
        run: cargo install --locked cargo-leptos

      - name: Build CSS
        run: |
          npm i
          npx @tailwindcss/cli -i ./src/web/server/static/input.css -o ./src/web/server/static/css/style.css

      # - name: Build web
      #   run: |
      #     cd src/web
      #     cargo leptos build -vv

      - name: Build backend
        run: cargo build --workspace

  test:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup default nightly
          rustup target add wasm32-unknown-unknown
          rustup upgrade

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ubuntu-24.04
          cache-all-crates: 'true'

      - name: Install cargo-leptos
        run: cargo install --locked cargo-leptos

      - name: Install cargo-llvm-cov
        run: cargo install --locked cargo-llvm-cov

      - name: Run tests
        run: RUST_BACKTRACE=1 cargo test -p api -p repos -p processor -p curator --no-fail-fast
