pub mod confirmation;
// pub mod crash;
// pub mod crashes;
pub mod datatable;
pub mod datatable_form;
pub mod datatable_header;
pub mod error_template;
pub mod login;
pub mod logout;
pub mod navbar;
pub mod passkey_logo;
pub mod products;
pub mod profile;
pub mod register;
// pub mod symbols;
// pub mod users;
// pub mod versions;
